PRIMARY = "#6B4EFF"
PRIMARY_LIGHT = "#9B7EFF"
PRIMARY_DARK = "#4A2FCC"
BACKGROUND = "#FFFFFF"
SURFACE = "#F8F7FF"
TEXT_PRIMARY = "#1A1A2E"
TEXT_SECONDARY = "#4A4A6A"
SUCCESS = "#10B981"
WARNING = "#F59E0B"
DANGER = "#EF4444"
INFO = "#3B82F6"

TITLE_FONT = ("Helvetica", 24, "bold")
HEADING_FONT = ("Helvetica", 18, "bold")
SUBHEADING_FONT = ("Helvetica", 14, "bold")
BODY_FONT = ("Helvetica", 12)
SMALL_FONT = ("Helvetica", 10)